// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_MainName;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_network;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_Panel1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_battery);
LV_FONT_DECLARE(ui_font_dinglie16);
LV_FONT_DECLARE(ui_font_headPortrait);
LV_FONT_DECLARE(ui_font_network);
LV_FONT_DECLARE(ui_font_status);
LV_FONT_DECLARE(ui_font_dinglie32);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
