/*** 
 * @Author: jixingnian@gmail.com
 * @Date: 2025-06-18 12:00:13
 * @LastEditTime: 2025-06-19 15:41:12
 * @LastEditors: 星年
 * @Description: 
 * @FilePath: \coze_ws_app_weixue\components\ui\ui_events.h
 * @遇事不决，可问春风
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"

extern SemaphoreHandle_t lvgl_mux;  // LVGL互斥锁

void ui_events_init(void);
void show_text(char *text);
void add_subtitle(char *text);
bool example_lvgl_lock(int timeout_ms);
void example_lvgl_unlock(void);

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif
#endif

